### ISSUE TITLE
Проблема с репозиторием

### ISSUE THREAD

**Issue by aleksandrbaranov1** [aleksandrbaranov1/Programming#11]
Здравствуйте!
У меня возникли проблемы с этим репозиторием. Перестало быть возможным использование его вместе с локальным репозиторием. Пытался исправить проблему своими силами, но ничего не вышло, а также из-за попытки решить эту проблему утеряна 6 работа. Предлагаю создать новый репозиторий.

**Comment by FlashAnton** [comment]
Здравствуйте!
А что Вы используете в качестве клиента для работы с репозиторием?
Как Вам удалось добиться эффекта, что очистилась история коммитов за начало декабря?
У меня, безусловно, сохранилась копия 6-й работы на одном из рабочих компьютеров и я смогу вернуть её Вам в том состоянии, в котором она была некоторое время тому назад. Но я всё равно не понимаю, каким образом могла очиститься история коммитов.

**Comment by aleksandrbaranov1** [comment]
Для работы с git использую терминал. Проблема состоит в том, что я перепутал команды. Хотел извлечь изменения из удаленного репозитория, и использовал для этого clone , а надо использовать pull. Начались какие-то конфликты, и я попробовал использовать push --force. После этого с помощью команды checkout был произведен возврат к одной из ранних версий репозитория. После чего был произведен комиит.

**Comment by FlashAnton** [comment]
Настоятельно рекомендую переходить на клиент. Например GitExtensions.
Там небезопасные команды на вряд ли применятся.
Я подтянул в репозитории с рабочего ПК Вашу работу №6 в том состоянии,
в котором она была в прошлую среду.
Склонируйте репозиторий в другой каталог на жёстком диске Вашего компьютера.
С высокой вероятностью теперь он начнёт работать нормально.
В прежнем не продолжайте. Там уже нарушились связи.

**Comment by aleksandrbaranov1** [comment]
Хорошо, большое спасибо
